version: '3.2'
services:
  web:
    build: .
    image: doromones/application_umbrella/server:latest
    command: mix phx.server
#    volumes:
#      - .:/home/app
    ports:
      - "4000:4000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: application_core_dev
