---
- name: Base provision
  hosts: application
  become: yes
  gather_facts: no
  pre_tasks:
    - name: apt update
      raw: sudo apt-get -y update
    - name: 'install python2'
      raw: sudo apt-get -y install python
  roles:
    - { role: erlang, tags: erlang }
    - { role: elixir, tags: elixir }
