---
- name: set erlang repository
  hosts: application
  become: yes
#  pre_tasks:
#    - name: apt update
#      raw: sudo apt-get -y update
#    - name: 'install python2'
#      raw: sudo apt-get -y install python
  roles:
    - { role: erlang, tags: erlang }
